name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: '0 3 * * *' # Once a day, 03:00 UTC.
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # See cflite_pr.yml for why this is address, not none or
          # coverage.
          sanitizer: coverage
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: 'batch'
          sanitizer: coverage
          output-sarif: true
